FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# DOerBox

DOerBox API is a simple API allowing users to view their todos.

## Session Collection [/api/web/session]

### Create a new session [POST]

+ Request (application/json)

        {
            email: 'youemail@email.com',
            password: 'your password md5'
        }

+ Response 200 (application/json)

        {
            success: true,
            message: '登录成功'
        }
        
+ Request (application/json)
    
        {
            email: 'error email address@email.com',
            password: 'or error password'
        }
        
+ Response 200 (application/json)

        {
            success: false,
            message: '账号或密码错误 or other error message'
        }

### Delete a session [DELETE]

+ Response 200 (application/json)

        {
            success: true,
            message: '注销成功'
        }
        
## Account Collection [/api/web/account]

### Create a new account [POST]

+ Request (application/json)

        {
            email: 'you email address',
            password: 'your password md5'
        }
        
+ Response 200 (application/json)

        {
            success: true,
            message: '注册成功'
        }
        
## Todo Collection [/api/web/todo]

### Create a todo [POST]

+ Request (application/json)

        {
            content: 'my todo content'
        }
        
+ Response 200 (application/json)

        {
            success: true,
            todo: {
                _id: '5123123453455sdfc',
                content: 'my todo content',
                tag_finish: false
            }
        }
        
### Update a todo [PUT]

+ Request (application/json)

        {
            _id: '5123123453455sdfc',
            content: 'new content',
            tag_finish: true
        }
        
+ Response 200 (application/json)

        {
            success: true,
            message: '更新成功'
        }
        
### Delete a todo [DELETE]

+ Request (application/json)

        {
            _id: '5123123453455sdfc'
        }
        
+ Response 200 (application/json)

        {
            success: true,
            message: '删除成功'
        }
        
## Todo List Collection [/api/web/todo_list]

### Get Todo List [GET]

+ Response 200 (application/json)

        {
            success: true,
            todos: [
                {
                    _id: '',
                    content: '',
                    tag_finish: true
                }
            ]
        }